name = "acrostic"
version = "1.2.1"

description = "A pure Gleam implementation of Google Protobuf."
licences = ["Apache-2.0"]
repository = { type = "github", user = "julywind168", repo = "acrostic" }

# links = [{ title = "Website", href = "" }]
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
nibble = ">= 1.1.1 and < 2.0.0"
sprinkle = ">= 1.0.1 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
